#!/bin/bash
set -e

echo "=========================================="
echo "Terraria Vanilla Server"
echo "=========================================="

# Check if version is set
if [ -z "${TERRARIA_VERSION}" ]; then
    echo "ERROR: TERRARIA_VERSION environment variable is required"
    echo "Example: TERRARIA_VERSION=1.4.5.1"
    exit 1
fi

echo "Version: ${TERRARIA_VERSION}"

# Download server if not present
if [ ! -f "/server/TerrariaServer.exe" ]; then
    echo "Server not found, downloading..."
    /download-server.sh
fi

# Map friendly names to Terraria's expected values
map_world_size() {
    case "${1,,}" in
        small|1)  echo "1" ;;
        medium|2) echo "2" ;;
        large|3)  echo "3" ;;
        *)        echo "3" ;; # Default to large
    esac
}

map_difficulty() {
    case "${1,,}" in
        classic|normal|0) echo "0" ;;
        expert|1)         echo "1" ;;
        master|2)         echo "2" ;;
        journey|3)        echo "3" ;;
        *)                echo "2" ;; # Default to master
    esac
}

CONFIG_FILE="${CONFIG_PATH}/serverconfig.txt"

# Check if config already exists (e.g., from helm init container)
if [ -f "${CONFIG_FILE}" ] && [ -s "${CONFIG_FILE}" ]; then
    echo "Using existing server configuration from ${CONFIG_FILE}"
    cat "${CONFIG_FILE}"
else
    # Generate server config from environment variables
    WORLD_SIZE_NUM=$(map_world_size "${WORLD_SIZE}")
    DIFFICULTY_NUM=$(map_difficulty "${DIFFICULTY}")

    echo "Generating server configuration..."

    cat > "${CONFIG_FILE}" << EOF
# Terraria Server Configuration
# Auto-generated by container

# World settings
world=${WORLD_PATH}/${WORLD_NAME}.wld
worldpath=${WORLD_PATH}
worldname=${WORLD_NAME}
autocreate=${WORLD_SIZE_NUM}
difficulty=${DIFFICULTY_NUM}

# Server settings
maxplayers=${MAX_PLAYERS}
port=${PORT}
secure=${SECURE}
language=${LANGUAGE}
upnp=${UPNP}
priority=${PRIORITY}
EOF

    # Add optional settings
    if [ -n "${PASSWORD}" ]; then
        echo "password=${PASSWORD}" >> "${CONFIG_FILE}"
    fi

    if [ -n "${MOTD}" ]; then
        echo "motd=${MOTD}" >> "${CONFIG_FILE}"
    fi
fi

echo ""
echo "Server Configuration:"
cat "${CONFIG_FILE}"
echo ""

# Extract world path from config for status message
WORLD_FILE=$(grep "^world=" "${CONFIG_FILE}" | cut -d'=' -f2)
if [ -f "${WORLD_FILE}" ]; then
    echo "Loading existing world: ${WORLD_FILE}"
else
    echo "World not found, will create new world"
fi

echo "Starting Terraria server..."
echo "=========================================="

# Run the server using native Linux binary
cd /server
exec ./TerrariaServer -config "${CONFIG_FILE}" "$@"
