#!/bin/bash
set -e

echo "=========================================="
echo "Terraria Vanilla Server v${TERRARIA_VERSION}"
echo "=========================================="

# Map friendly names to Terraria's expected values
map_world_size() {
    case "${1,,}" in
        small|1)  echo "1" ;;
        medium|2) echo "2" ;;
        large|3)  echo "3" ;;
        *)        echo "3" ;; # Default to large
    esac
}

map_difficulty() {
    case "${1,,}" in
        classic|normal|0) echo "0" ;;
        expert|1)         echo "1" ;;
        master|2)         echo "2" ;;
        journey|3)        echo "3" ;;
        *)                echo "2" ;; # Default to master
    esac
}

WORLD_SIZE_NUM=$(map_world_size "${WORLD_SIZE}")
DIFFICULTY_NUM=$(map_difficulty "${DIFFICULTY}")

# Generate server config
CONFIG_FILE="${CONFIG_PATH}/serverconfig.txt"

echo "Generating server configuration..."

cat > "${CONFIG_FILE}" << EOF
# Terraria Server Configuration
# Auto-generated by container

# World settings
world=${WORLD_PATH}/${WORLD_NAME}.wld
worldpath=${WORLD_PATH}
worldname=${WORLD_NAME}
autocreate=${WORLD_SIZE_NUM}
difficulty=${DIFFICULTY_NUM}

# Server settings
maxplayers=${MAX_PLAYERS}
port=${PORT}
secure=${SECURE}
language=${LANGUAGE}
upnp=${UPNP}
priority=${PRIORITY}
EOF

# Add optional settings
if [ -n "${PASSWORD}" ]; then
    echo "password=${PASSWORD}" >> "${CONFIG_FILE}"
fi

if [ -n "${MOTD}" ]; then
    echo "motd=${MOTD}" >> "${CONFIG_FILE}"
fi

echo ""
echo "Server Configuration:"
echo "  World: ${WORLD_NAME}"
echo "  Size: ${WORLD_SIZE} (${WORLD_SIZE_NUM})"
echo "  Difficulty: ${DIFFICULTY} (${DIFFICULTY_NUM})"
echo "  Max Players: ${MAX_PLAYERS}"
echo "  Port: ${PORT}"
echo ""

# Check if world exists
if [ -f "${WORLD_PATH}/${WORLD_NAME}.wld" ]; then
    echo "Loading existing world: ${WORLD_NAME}"
else
    echo "World not found, will create new world: ${WORLD_NAME}"
fi

echo "Starting Terraria server..."
echo "=========================================="

# Run the server
cd /server
exec mono TerrariaServer.exe -config "${CONFIG_FILE}" "$@"
